---

setup__apt__sources:
  - name: jessie-backports.list
    content: |
      # jessie-backports, previously on backports.debian.org
      deb http://ftp.ru.debian.org/debian/ jessie-backports main contrib non-free
      deb-src http://ftp.ru.debian.org/debian/ jessie-backports main contrib non-free
