---

- name: Add apt sources for ISP
  copy:
    dest: '/etc/apt/sources.list.d/{{ item.name }}'
    content: '{{ item.content }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - name: ispsystem-base.list
      content: 'deb http://download.ispsystem.com/repo/debian base-jessie main'
    - name: ispsystem.list
      content: 'deb http://download.ispsystem.com/repo/debian 5.86-jessie main'

- name: Add apt key for ISP
  apt_key:
    url: "http://cdn.ispsystem.com/repo/debian/ispsystem.gpg.key"
    state: present

- name: Install ispmanager-lite-common
  apt:
    name: ispmanager-lite-common
    state: present
    update_cache: yes

- name: ihttpd listen on all interfaces
  copy:
    dest: /usr/local/mgr5/etc/ihttpd.conf
    content: |
      listen {
        ip *
        redirect
      }

    owner: root
    group: root
    backup: yes
    mode: 0644
  notify: restart ihttpd

- name: Allow weak passwords in ISP
  lineinfile:
    path: /usr/local/mgr5/etc/ispmgr.conf
    regexp: '^PWStrength'
    line: 'PWStrength 0'
  notify: restart coremanager

- block:
  - name: Check "support" admin
    command: /usr/local/mgr5/sbin/mgrctl -m ispmgr admin
    register: mgrctl__admin__result

  - name: Add "support" admin
    command: /usr/local/mgr5/sbin/mgrctl -m ispmgr admin.edit name=support passwd=oper confirm=oper super=on sok=ok
    when: '"name=support" not in mgrctl__admin__result.stdout'

- name: Install packages for ISP
  package:
    name: '{{ item.name }}'
    state: '{{ item.state | d(omit) }}'
  with_items:
    - name: exim4-daemon-heavy
    - name: ispmanager-pkg-exim

    - name: ispmanager-pkg-afterlogic
    - name: ispmanager-pkg-bind
    - name: ispmanager-pkg-dovecot
    - name: ispmanager-pkg-httpd-itk
    - name: ispmanager-pkg-logrotate
    - name: ispmanager-pkg-myadmin
    - name: ispmanager-pkg-mysql
    - name: ispmanager-pkg-nginx
    - name: ispmanager-pkg-php
    - name: ispmanager-pkg-proftpd
    - name: ispmanager-pkg-quota

- block:
  - name: Check "dev" user
    command: /usr/local/mgr5/sbin/mgrctl -m ispmgr user
    register: mgrctl__user__result

  - name: Create "dev" user
    command: >
      /usr/local/mgr5/sbin/mgrctl -m ispmgr
      user.edit
      name=dev
      passwd=dev confirm=dev
      limit_shell=on
      limit_ssl=on
      limit_cgi=on
      limit_php_mode_cgi=on
      sok=ok
      {% if "name=dev" in mgrctl__user__result.stdout %}elid=dev{% endif %}

- block:
  - name: Check "dev.localhost"
    command: /usr/local/mgr5/sbin/mgrctl -m ispmgr webdomain
    register: mgrctl__webdomain__result

  - name: Create "dev.localhost"
    command: >
      /usr/local/mgr5/sbin/mgrctl -m ispmgr
      webdomain.edit
      name=dev.localhost
      home=dev.localhost
      email=webmaster@dev.localhost
      ssi=on
      cgi=on
      htaccess=on
      srv_gzip=on
      gzip_level=5
      foreground=on
      srv_cache=on
      expire_times=expire_times_max
      sok=ok
      {% if "name=dev.localhost" in mgrctl__webdomain__result.stdout %}elid=dev.localhost{% endif %}
