---

- name: system
  include: system.yml

- name: mysql
  include: mysql.yml

- name: openssl + nginx
  include: nginx/nginx-8.x.yml
  when: ansible_distribution_major_version | int <= 8

- name: openssl + nginx
  include: nginx/nginx-9.x.yml
  when: ansible_distribution_major_version | int > 8

- name: isp
  include: ispsystem.yml
