---

- name: Install openssl
  apt:
    state: present
    name: openssl=1.0.2k*
    default_release: jessie-backports
    update_cache: yes

- name: Install nginx
  apt:
    state: present
    name: nginx=1.10*
    default_release: jessie-backports
    update_cache: yes

- name: Hold nginx
  command: apt-mark hold nginx
