---

- name: Add apt sources
  copy:
    dest: '/etc/apt/sources.list.d/{{ item.name }}'
    content: '{{ item.content }}'
    owner: root
    group: root
    mode: 0644
  with_items: '{{ setup__apt__sources }}'
  register: setup__apt__sources__result

- name: Force apt cache update
  apt:
    update_cache: yes
  when: setup__apt__sources__result | changed

- name: Manage packages
  apt:
    state: '{{ item.state | d("present") }}'
    name: '{{ item.name }}'
    default_release: '{{ item.default_release | d(omit) }}'
    update_cache: '{{ item.update_cache | d(omit) }}'
    purge: '{{ item.purge | d(omit) }}'
  with_items:
    # cant update kernel - vboxadd kernel module will broke
    # - name: linux-image-amd64=4.9*
    #   state: present
    #   default_release: jessie-backports
    #   # update_cache: yes
    - name: screen
